### ISSUE TITLE
Invalid assumption of SocketAddrV{4,6} layout

### ISSUE THREAD

**Issue by Nemo157** [stjepang/nb-connect#1]
This code assumes that Rust's `std::net::{SocketAddrV4, SocketAddrV6}` are layout compatible with `sockaddr`:

https://github.com/smol-rs/nb-connect/blob/f706c11d75fbdae0ac7fe633f3bf7390bd4f79c5/src/lib.rs#L61-L84

This is not guaranteed by the standard library, see https://github.com/rust-lang/rust/pull/78802 for more details.

**Comment by faern** [comment]
Awesome :tada:
Will there be a semver compatible patch release coming out? So people can get rid of the invalid memory assumption with a simple `cargo update`.

**Comment by taiki-e** [comment]
Published in 1.0.3 & yanked old versions.

**Comment by faern** [comment]
Thanks!

**Comment by faern** [comment]
I submitted a security advisory on the older versions. https://github.com/RustSec/advisory-db/pull/765
